apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kaniko
  namespace: argo-workflows
rules:
- apiGroups:
    - argoproj.io
  resources:
    - workflowtaskresults
  verbs:
    - create
    - patch
