apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: busybox
spec:
  host: busybox-argo-events.apps.baloise.dev
  path: /
  port:
    targetPort: busybox
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: github-eventsource-svc
    weight: 100
  wildcardPolicy: None
