apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: busybox
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: busybox
      eventSourceName: github
      eventName: busybox
  triggers:
    - template:
        name: webhook-workflow-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: busybox-  
              spec:
                serviceAccountName: kaniko
                entrypoint: build
                volumes:
                - name: kaniko-secret
                  secret:
                    secretName: credentials
                    items:
                      - key: .dockerconfigjson
                        path: config.json
                templates:
                - name: build
                  dag:
                    tasks:
                    - name: build
                      templateRef:
                        name: container-image
                        template: build-kaniko-git
                        clusterScope: true
                      arguments:
                        parameters:
                        - name: repo
                          value: git://github.com/Baloise-CodeCamp-2022/flux-de-travail
                        - name: dockerfile
                          value: https://raw.githubusercontent.com/Baloise-CodeCamp-2022/flux-de-travail/main/image-build/Dockerfile
                        - name: container_image
                          value: registry.baloise.dev/argo-workflows/busybox
                        - name: container_tag
                          value: "1.0.0"