apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: container-image
spec:
  securityContext:
    runAsUser: 0
  serviceAccountName: kaniko
  templates:
  - name: build-kaniko-git
    inputs:
      parameters:
      - name: repo
      - name: container_image
      - name: container_tag
      - name: dockerfile
    container:
      securityContext:
        runAsUser: 0
      image: gcr.io/kaniko-project/executor:debug
      command: [/kaniko/executor]
      args:
      - --context={{inputs.parameters.repo}}
      - --dockerfile={{inputs.parameters.dockerfile}}
      - --destination={{inputs.parameters.container_image}}:{{inputs.parameters.container_tag}}
      volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker/
  